spring:
  application:
    name: birt-report
  profiles: 
    active: DEV
  main:
    banner-mode: console
server:
  http2:
    enabled: true
  port: 1991
  shutdown: graceful
logging:
  level:
    '[com.thirumal]': debug
  file:
    path: logs
    name: logs/birt-report.log
  logback: 
    rollingpolicy: 
      max-history: 10
      max-file-size: 100MB
      total-size-cap: 1GB
